trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: python -m pip install --upgrade pip
  displayName: 'Upgrade pip'

- script: pip install -r requirements.txt
  displayName: 'Install requirements'

- script: |
    pip install pytest
    pip install pytest-cov
    pytest ./resample/tests --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
  displayName: 'Run tests'
